apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    name: webservice
spec:
  type: LoadBalancer
  selector:
    app: myapp
  ports:
    - protocol: TCP
      targetPort: 5000
      port: 80
