apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: pyapp
        image: us-west4-docker.pkg.dev/centering-keep-391803/pyapp/testpyapp:1.2
        ports:
        - containerPort: 5000
